config/routes.rb
Rails.application.routes.draw do
  root to: 'searches#new'
  scope do
    resources :searches, only: [:new, :create, :show], param: :term, path: :search
  end
  get '/searches', to: 'searches#index', as: :search_history
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  validates :term, presence: true

  def results
    @results ||= GoodReads.search(term)
  end
end

app/models/search_history.rb
class SearchHistory < ApplicationRecord
  def date
    latest_date.strftime('%B %e, %Y %l:%M %P')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :navigation

  def navigation
    if request.path == root_path
      ["Search History", search_history_path]
    else
      ["Home", root_path]
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  helper_method :sort_field, :sort_direction

  def index
    @searches = SearchHistory.order("#{sort_field} #{sort_direction}")
  end

  def show
    @search = Search.find_by(term: params[:term])
  end

  def new; end

  def create
    @search = Search.new(search_params)
    if @search.save
      redirect_to search_path(term: @search.term)
    else
      render :new
    end
  end

  private

  def search_params
    params.require(:search).permit(:term)
  end

  def sortable_fields
    ["latest_date", "search_count", "term"]
  end

  def sort_field
    sortable_fields.include?(params[:field]) ? params[:field] : "term"
  end

  def sort_direction
    ["asc", "desc"].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
  def searches_with_counts
    Search.group(:term).count
  end

  def previous_search_dates(term)
    Search.where(term: term).pluck(:created_at).map do |date|
      date.strftime('%B %e, %Y %l:%M %P')
    end
  end

  def link_to_sort(field, title=nil)
    title ||= field.titleize
    direction = field == sort_field && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {field: field, direction: direction}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= link_to *navigation %>
    <div class="flex-container">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end -%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/index.html.erb
<div class="content">
  <table>
    <tr>
      <th><%= link_to_sort "search_count", "Count" %></th>
      <th><%= link_to_sort "term" %></th>
      <th><%= link_to_sort "latest_date", "Date" %></th>
    </tr>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.search_count %></td>
        <td><%= button_to search.term, searches_path(search: { term: search.term }) %></td>
        <td><%= search.date %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/searches/new.html.erb
<div class="sidebar">
  <table>
    <tr>
      <th>Count</th>
      <th>Search</th>
    </tr>
    <% searches_with_counts.each do |term, count| %>
      <tr>
        <td><%= count %></td>
        <td><%= button_to term, searches_path(search: { term: term }) %></td>
      </tr>
    <% end %>
  </table>
</div>
<div class="content">
  <%= form_for :search, url: searches_path do |f| %>
    <%= @search&.errors&.full_messages_for(:term)&.first %>
    <%= f.text_field :term %>
    <%= f.submit "Search" %>
  <% end %>
</div>

app/views/searches/show.html.erb
<div class="sidebar">
  <table>
    <tr>
      <th>Searched on:</th>
    </tr>
    <% previous_search_dates(@search.term).each do |date| %>
      <tr>
        <td><%= date %></td>
      </tr>
    <% end %>
  </table>
</div>
<div class="content">
  <h1>Searched for: <%= @search.term %></h1>
  <h2>Goodreads Book Results</h2>
  <table>
    <tr>
      <th></th>
      <th>title</th>
      <th>author</th>
      <th>ratings</th>
      <th>average rating</th>
    </tr>
    <% @search.results.each do |result| %>
      <tr>
        <td><%= image_tag result.image_url, alt: "#{result.title} cover" %></td>
        <td><%= result.title %></td>
        <td><%= result.author %></td>
        <td><%= result.ratings %></td>
        <td><%= result.average_rating %></td>
      </tr>
    <% end %>
  </table>
</div>